"""
STORM Async Core — 多渠道全格式一键导出引擎 (MultiFormatExporter)
功能：
1. 一键生成 Marp 学术演讲幻灯片 (Slides Markdown / PPT)
2. 一键生成自包含排版的独立离线 HTML 学术研报（内嵌暗黑/明亮打印样式，支持无损转存 Word/印刷）
"""

import html
import json
import logging
import re
from pathlib import Path
from typing import Dict, Any, Optional

from .models import ArticleDraft

logger = logging.getLogger(__name__)


class MultiFormatExporter:
    """多格式出版物导出器。"""

    def generate_marp_slides_markdown(self, draft: ArticleDraft) -> str:
        """根据文章大纲与核心论点生成 Marp 幻灯片源文件。"""
        topic = draft.topic
        sections = draft.outline.sections if draft.outline else []

        slides = [
            "---",
            "marp: true",
            "theme: gaia",
            "_class: lead",
            "paginate: true",
            "backgroundColor: #0f172a",
            "color: #f8fafc",
            "---",
            f"\n# {topic}\n",
            "### 深度知识策展与学术长文研报",
            "\n*STORM Deep Research Agent 自动编排生成*\n",
            "---",
            "\n## 📋 目录导航 (Table of Contents)\n",
        ]

        for idx, sec in enumerate(sections, start=1):
            slides.append(f"{idx}. **{sec.title}**")

        slides.append("\n---")

        # 为每个主要 Section 生成一页 Slide
        body = draft.polished_content or draft.content
        for sec in sections:
            slides.append(f"\n## 📌 {sec.title}\n")
            # 提取该章节下的前 2~3 个核心句子作为 Bullet Points
            pattern = rf"##\s+{re.escape(sec.title)}\s*\n([\s\S]+?)(?=\n##\s+|$)"
            match = re.search(pattern, body)
            if match:
                sec_text = match.group(1).strip()
                # 过滤引用标记并切分要点
                clean_text = re.sub(r'\[\d+\]', '', sec_text)
                paragraphs = [p.strip() for p in clean_text.split("\n\n") if p.strip()]
                for p in paragraphs[:3]:
                    if not p.startswith("#") and not p.startswith("|"):
                        slides.append(f"- {p[:120]}...")
            else:
                slides.append(f"- 深入探讨 {sec.title} 的关键机制与学术实证。")
            slides.append("\n---")

        # 最后一页：参考文献概览
        slides.append("\n## 📚 核心参考文献 (Key Citations)\n")
        for idx, item in sorted(list(draft.citations.items())[:6], key=lambda x: x[0]):
            slides.append(f"- **[{idx}]** [{item['title']}]({item['url']})")

        slides.append("\n---")
        slides.append("\n# ✨ 谢谢大家 / Q&A\n\n*Generated by STORM Architecture*")
        return "\n".join(slides)

    def generate_standalone_html_report(self, draft: ArticleDraft) -> str:
        """生成自包含、零外部网络依赖且防 XSS 注入的独立 HTML 研报（含印刷样式）。"""
        topic_escaped = html.escape(draft.topic)
        content_md = draft.polished_content or draft.content

        # 提取 Mermaid 代码块
        mermaid_blocks = []
        def _save_mermaid(m):
            idx = len(mermaid_blocks)
            mermaid_blocks.append(m.group(1).strip())
            return f"__MERMAID_BLOCK_{idx}__"

        content_md = re.sub(r"```(?:mermaid)?\s*\n([\s\S]*?)\n```", _save_mermaid, content_md)

        def _format_inline(text: str) -> str:
            # 1. 基础 HTML 转义防 XSS
            safe = html.escape(text)
            # 2. 加粗 **text**
            safe = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', safe)
            # 3. 行内代码 `code`
            safe = re.sub(r'`([^`]+)`', r'<code>\1</code>', safe)
            # 4. 引用标号 [1]
            safe = re.sub(r'\[(\d+)\]', r'<sup class="citation">[\1]</sup>', safe)
            return safe

        html_body = []
        for line in content_md.split("\n"):
            line_s = line.strip()
            if not line_s:
                continue

            if line_s.startswith("__MERMAID_BLOCK_"):
                m_idx_match = re.search(r'__MERMAID_BLOCK_(\d+)__', line_s)
                if m_idx_match:
                    m_idx = int(m_idx_match.group(1))
                    if m_idx < len(mermaid_blocks):
                        raw_code = html.escape(mermaid_blocks[m_idx])
                        html_body.append(f'<div class="mermaid-box"><pre class="mermaid">{raw_code}</pre></div>')
                continue

            if line_s.startswith("# "):
                html_body.append(f"<h1>{_format_inline(line_s[2:])}</h1>")
            elif line_s.startswith("## "):
                html_body.append(f"<h2>{_format_inline(line_s[3:])}</h2>")
            elif line_s.startswith("### "):
                html_body.append(f"<h3>{_format_inline(line_s[4:])}</h3>")
            elif line_s.startswith("> "):
                html_body.append(f"<blockquote><p>{_format_inline(line_s[2:])}</p></blockquote>")
            elif line_s.startswith("- ") or line_s.startswith("• ") or line_s.startswith("* "):
                html_body.append(f"<li>{_format_inline(line_s[2:])}</li>")
            elif line_s.startswith("| ") and "|" in line_s:
                html_body.append(f"<code>{html.escape(line_s)}</code><br>")
            else:
                html_body.append(f"<p>{_format_inline(line_s)}</p>")

        body_html_str = "\n".join(html_body)

        html_doc = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>{topic_escaped} - STORM 深度研报</title>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <style>
    @media print {{
      body {{ background: #fff !important; color: #000 !important; }}
      .no-print {{ display: none !important; }}
      @page {{ margin: 2cm; }}
    }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Songti SC", sans-serif;
      line-height: 1.8;
      max-width: 860px;
      margin: 40px auto;
      padding: 0 24px;
      background: #0b0f19;
      color: #e2e8f0;
    }}
    h1 {{ font-size: 28px; border-bottom: 2px solid #334155; padding-bottom: 12px; color: #fff; }}
    h2 {{ font-size: 20px; color: #818cf8; margin-top: 32px; border-bottom: 1px solid #1e293b; padding-bottom: 6px; }}
    h3 {{ font-size: 16px; color: #cbd5e1; margin-top: 24px; }}
    p {{ margin-bottom: 16px; text-align: justify; }}
    blockquote {{ border-left: 3px solid #6366f1; background: #131b2e; padding: 12px 16px; margin: 16px 0; border-radius: 0 6px 6px 0; }}
    blockquote p {{ margin-bottom: 0; color: #cbd5e1; }}
    sup.citation {{ color: #a5b4fc; font-weight: bold; margin: 0 2px; }}
    .header-badge {{ background: #1e1b4b; color: #818cf8; padding: 4px 10px; border-radius: 4px; font-size: 12px; display: inline-block; margin-bottom: 16px; }}
    .mermaid-box {{ background: #12161f; border: 1px solid #334155; border-radius: 8px; padding: 20px; margin: 24px 0; display: flex; justify-content: center; }}
    .citations-section {{ margin-top: 48px; border-top: 2px solid #334155; padding-top: 24px; }}
    .citation-item {{ font-size: 13px; color: #94a3b8; margin-bottom: 8px; }}
    .citation-item a {{ color: #818cf8; text-decoration: none; }}
  </style>
</head>
<body>
  <div class="header-badge">STORM Deep Research Report</div>
  {body_html_str}
  <div class="citations-section">
    <h2>References & Sources</h2>
"""
        for idx, item in sorted(draft.citations.items(), key=lambda x: x[0]):
            url = html.escape(item.get("url", "#"))
            title = html.escape(item.get("title", url))
            html_doc += f'    <div class="citation-item">[{idx}] <a href="{url}" target="_blank" rel="noopener noreferrer">{title}</a></div>\n'

        html_doc += """  </div>
  <script>
    if (window.mermaid) {
      mermaid.initialize({ startOnLoad: true, theme: 'dark' });
    }
  </script>
</body>
</html>"""
        return html_doc
