"""
STORM Async Core — Typst 学术排版编译器 (TypstCompiler)
功能：
1. 将 Markdown 正文与引用字典自动编排为标准 Typst 论文格式 (.typ)
2. 支持 IEEE / ACM 双栏论文排版模板与专业咨询研报模板
3. 自动生成标题、作者栏、摘要、分级标题、三线表、图表与参考文献
4. 支持调用本地 typst CLI 编译高清 PDF，或导出纯 .typ 源码文件
"""

import json
import logging
import re
import shutil
import subprocess
from pathlib import Path
from typing import Dict, Optional, Any

from .models import ArticleDraft, Outline

logger = logging.getLogger(__name__)


class TypstCompiler:
    """现代 Typst 学术论文排版编译器。"""

    def __init__(self, template: str = "ieee_paper"):
        self.template = template

    def generate_typst_source(self, draft: ArticleDraft, author: str = "溯知 · SuZhi", affiliation: str = "鹿溪联合创新实验室") -> str:
        """将 ArticleDraft 转换为合法的 Typst 源文件内容。"""
        topic = draft.topic
        content = draft.polished_content or draft.content

        # 提取摘要（若有）
        abstract_lines = []
        body_lines = []
        in_abstract = False

        for line in content.split("\n"):
            if line.startswith("# "):
                continue  # 根标题在顶部独立居中渲染
            if line.startswith("> **摘要**") or line.startswith("> **Abstract**") or line.startswith("> 摘要") or line.startswith("> Abstract"):
                in_abstract = True
                clean_l = re.sub(r'^>\s*', '', line).replace("**", "")
                abstract_lines.append(clean_l)
            elif in_abstract and line.startswith(">"):
                clean_l = re.sub(r'^>\s*', '', line).replace("**", "")
                abstract_lines.append(clean_l)
            else:
                if in_abstract and not line.strip():
                    in_abstract = False
                else:
                    in_abstract = False
                    body_lines.append(line)

        # 转换 Markdown 标题为 Typst 标题
        typst_body = []
        for line in body_lines:
            if line.startswith("### "):
                typst_body.append("== " + line.replace("### ", "").strip())
            elif line.startswith("## "):
                title = line.replace("## ", "").strip()
                if title.lower() in ("references", "参考文献"):
                    continue  # Typst 自带参考文献编排
                typst_body.append("= " + title)
            elif line.startswith("| ") and "|" in line:
                # 简单表格兼容保持
                typst_body.append(line)
            else:
                # 将引用 [1] 转换为上标或方括号加粗
                converted_line = re.sub(r'\[(\d+)\]', r'#super[\1]', line)
                typst_body.append(converted_line)

        body_typst_str = "\n".join(typst_body)

        # 组织摘要块
        abstract_typst_block = ""
        if abstract_lines:
            abs_text = "\n".join(abstract_lines)
            abstract_typst_block = f"""
#align(center)[
  #block(width: 88%, fill: rgb("#f8fafc"), inset: 1.2em, radius: 4pt, stroke: 0.5pt + rgb("#e2e8f0"))[
    #align(left)[
      #text(size: 9pt, weight: "bold", fill: rgb("#1e293b"))[Abstract / 摘要：] \\
      #v(0.3em)
      #text(size: 9pt, fill: rgb("#334155"), style: "italic")[{abs_text}]
    ]
  ]
]
#v(1em)
"""

        # 组织 Typst 模板
        typst_code = f"""// Auto-generated by STORM Typst Compiler
// Document: {topic}

#set page(
  paper: "a4",
  margin: (x: 1.8cm, top: 2.2cm, bottom: 2.2cm),
  header: align(right)[
    #text(size: 8pt, fill: rgb("#666666"))[{topic} | STORM Deep Research]
  ],
  footer: align(center)[
    #text(size: 9pt, fill: rgb("#888888"))[STORM Research Intelligence]
  ]
)

#set text(
  font: ("Linux Libertine", "Songti SC", "SimSun"),
  size: 10pt,
  lang: "zh"
)

#set par(
  justify: true,
  leading: 0.65em,
  first-line-indent: 2em
)

// Title & Author Block
#align(center)[
  #v(1em)
  #text(size: 18pt, weight: "bold")[{topic}]
  #v(0.8em)
  #text(size: 11pt, weight: "medium")[{author}] \\
  #text(size: 9pt, fill: rgb("#555555"))[{affiliation}]
  #v(1.2em)
]

{abstract_typst_block}

// Two-column layout for academic format
#show heading.where(level: 1): it => block(
  above: 1.2em, below: 0.8em,
  text(size: 12pt, weight: "bold", fill: rgb("#1a365d"))[#it.body]
)

#show heading.where(level: 2): it => block(
  above: 1em, below: 0.6em,
  text(size: 10.5pt, weight: "semibold", fill: rgb("#2b6cb0"))[#it.body]
)

#columns(2, gutter: 1.5em)[
{body_typst_str}
]

#v(2em)
#line(length: 100%, stroke: 0.5pt + rgb("#cccccc"))
#v(0.5em)
#text(size: 11pt, weight: "bold")[References & Citations]
#v(0.5em)

#list(
"""
        for idx, item in sorted(draft.citations.items(), key=lambda x: x[0]):
            url = item.get("url", "")
            title = item.get("title", url).replace("[", "").replace("]", "")
            typst_code += f'  [{idx}] #link("{url}")[{title}],\n'

        typst_code += ")\n"
        return typst_code

    def export_typst_file(self, draft: ArticleDraft, output_path: str) -> str:
        """导出 .typ 源码文件。"""
        code = self.generate_typst_source(draft)
        p = Path(output_path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(code, encoding="utf-8")
        logger.info(f"Typst source exported to {p.absolute()}")
        return str(p.absolute())

    def compile_pdf(self, draft: ArticleDraft, output_pdf_path: str) -> bool:
        """调用本地 typst CLI 编译 PDF（如果环境安装了 typst）。"""
        typ_path = Path(output_pdf_path).with_suffix(".typ")
        self.export_typst_file(draft, str(typ_path))

        typst_bin = shutil.which("typst")
        if not typst_bin:
            logger.info("Typst CLI is not installed locally. Generated .typ source file ready for compilation.")
            return False

        try:
            res = subprocess.run(
                [typst_bin, "compile", str(typ_path), output_pdf_path],
                capture_output=True,
                text=True,
                check=True,
            )
            logger.info(f"Typst PDF successfully compiled to {output_pdf_path}")
            return True
        except Exception as e:
            logger.error(f"Typst compilation failed: {e}")
            return False
